// flow-typed signature: a9c5d0b67d0aff69a0e05be6f073bddd
// flow-typed version: <<STUB>>/express-pino-logger_v^4.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-pino-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-pino-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-pino-logger/benchmarks/bunyan-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/benchmarks/express-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/benchmarks/morgan-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/benchmarks/no-log-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/benchmarks/pino-extreme-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/benchmarks/pino-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/benchmarks/raw-extreme-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/benchmarks/raw-just-pino-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/benchmarks/raw-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/benchmarks/winston-server' {
  declare module.exports: any;
}

declare module 'express-pino-logger/example' {
  declare module.exports: any;
}

declare module 'express-pino-logger/logger' {
  declare module.exports: any;
}

declare module 'express-pino-logger/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-pino-logger/benchmarks/bunyan-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/bunyan-server'>;
}
declare module 'express-pino-logger/benchmarks/express-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/express-server'>;
}
declare module 'express-pino-logger/benchmarks/morgan-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/morgan-server'>;
}
declare module 'express-pino-logger/benchmarks/no-log-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/no-log-server'>;
}
declare module 'express-pino-logger/benchmarks/pino-extreme-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/pino-extreme-server'>;
}
declare module 'express-pino-logger/benchmarks/pino-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/pino-server'>;
}
declare module 'express-pino-logger/benchmarks/raw-extreme-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/raw-extreme-server'>;
}
declare module 'express-pino-logger/benchmarks/raw-just-pino-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/raw-just-pino-server'>;
}
declare module 'express-pino-logger/benchmarks/raw-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/raw-server'>;
}
declare module 'express-pino-logger/benchmarks/winston-server.js' {
  declare module.exports: $Exports<'express-pino-logger/benchmarks/winston-server'>;
}
declare module 'express-pino-logger/example.js' {
  declare module.exports: $Exports<'express-pino-logger/example'>;
}
declare module 'express-pino-logger/logger.js' {
  declare module.exports: $Exports<'express-pino-logger/logger'>;
}
declare module 'express-pino-logger/test.js' {
  declare module.exports: $Exports<'express-pino-logger/test'>;
}
