// flow-typed signature: 465bc25d9b968d985c538c6584b2638d
// flow-typed version: <<STUB>>/ganache-core_v^2.4.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ganache-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ganache-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ganache-core/build/ganache.core.node' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/block_tracker' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/blockchain_double' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database/blocklogsserializer' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database/blockserializer' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database/bufferserializer' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database/filedown' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database/leveluparrayadapter' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database/levelupobjectadapter' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database/levelupvalueadapter' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database/receiptserializer' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/database/txserializer' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/httpServer' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/provider' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/server' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/statemanager' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/subproviders/delayedblockfilter' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/subproviders/geth_api_double' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/subproviders/gethdefaults' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/subproviders/reactiveblocktracker' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/subproviders/requestfunnel' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/block_helper' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/errorhelper' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/forkedblockchain' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/forkedstoragetrie' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/log' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/random' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/receipt' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/runtimeerror' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/to' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/transaction' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/utils/txrejectederror' {
  declare module.exports: any;
}

declare module 'ganache-core/lib/webSocketServer' {
  declare module.exports: any;
}

declare module 'ganache-core/public-exports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ganache-core/build/ganache.core.node.js' {
  declare module.exports: $Exports<'ganache-core/build/ganache.core.node'>;
}
declare module 'ganache-core/index' {
  declare module.exports: $Exports<'ganache-core'>;
}
declare module 'ganache-core/index.js' {
  declare module.exports: $Exports<'ganache-core'>;
}
declare module 'ganache-core/lib/block_tracker.js' {
  declare module.exports: $Exports<'ganache-core/lib/block_tracker'>;
}
declare module 'ganache-core/lib/blockchain_double.js' {
  declare module.exports: $Exports<'ganache-core/lib/blockchain_double'>;
}
declare module 'ganache-core/lib/database.js' {
  declare module.exports: $Exports<'ganache-core/lib/database'>;
}
declare module 'ganache-core/lib/database/blocklogsserializer.js' {
  declare module.exports: $Exports<'ganache-core/lib/database/blocklogsserializer'>;
}
declare module 'ganache-core/lib/database/blockserializer.js' {
  declare module.exports: $Exports<'ganache-core/lib/database/blockserializer'>;
}
declare module 'ganache-core/lib/database/bufferserializer.js' {
  declare module.exports: $Exports<'ganache-core/lib/database/bufferserializer'>;
}
declare module 'ganache-core/lib/database/filedown.js' {
  declare module.exports: $Exports<'ganache-core/lib/database/filedown'>;
}
declare module 'ganache-core/lib/database/leveluparrayadapter.js' {
  declare module.exports: $Exports<'ganache-core/lib/database/leveluparrayadapter'>;
}
declare module 'ganache-core/lib/database/levelupobjectadapter.js' {
  declare module.exports: $Exports<'ganache-core/lib/database/levelupobjectadapter'>;
}
declare module 'ganache-core/lib/database/levelupvalueadapter.js' {
  declare module.exports: $Exports<'ganache-core/lib/database/levelupvalueadapter'>;
}
declare module 'ganache-core/lib/database/receiptserializer.js' {
  declare module.exports: $Exports<'ganache-core/lib/database/receiptserializer'>;
}
declare module 'ganache-core/lib/database/txserializer.js' {
  declare module.exports: $Exports<'ganache-core/lib/database/txserializer'>;
}
declare module 'ganache-core/lib/httpServer.js' {
  declare module.exports: $Exports<'ganache-core/lib/httpServer'>;
}
declare module 'ganache-core/lib/provider.js' {
  declare module.exports: $Exports<'ganache-core/lib/provider'>;
}
declare module 'ganache-core/lib/server.js' {
  declare module.exports: $Exports<'ganache-core/lib/server'>;
}
declare module 'ganache-core/lib/statemanager.js' {
  declare module.exports: $Exports<'ganache-core/lib/statemanager'>;
}
declare module 'ganache-core/lib/subproviders/delayedblockfilter.js' {
  declare module.exports: $Exports<'ganache-core/lib/subproviders/delayedblockfilter'>;
}
declare module 'ganache-core/lib/subproviders/geth_api_double.js' {
  declare module.exports: $Exports<'ganache-core/lib/subproviders/geth_api_double'>;
}
declare module 'ganache-core/lib/subproviders/gethdefaults.js' {
  declare module.exports: $Exports<'ganache-core/lib/subproviders/gethdefaults'>;
}
declare module 'ganache-core/lib/subproviders/reactiveblocktracker.js' {
  declare module.exports: $Exports<'ganache-core/lib/subproviders/reactiveblocktracker'>;
}
declare module 'ganache-core/lib/subproviders/requestfunnel.js' {
  declare module.exports: $Exports<'ganache-core/lib/subproviders/requestfunnel'>;
}
declare module 'ganache-core/lib/utils/block_helper.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/block_helper'>;
}
declare module 'ganache-core/lib/utils/errorhelper.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/errorhelper'>;
}
declare module 'ganache-core/lib/utils/forkedblockchain.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/forkedblockchain'>;
}
declare module 'ganache-core/lib/utils/forkedstoragetrie.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/forkedstoragetrie'>;
}
declare module 'ganache-core/lib/utils/log.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/log'>;
}
declare module 'ganache-core/lib/utils/random.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/random'>;
}
declare module 'ganache-core/lib/utils/receipt.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/receipt'>;
}
declare module 'ganache-core/lib/utils/runtimeerror.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/runtimeerror'>;
}
declare module 'ganache-core/lib/utils/to.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/to'>;
}
declare module 'ganache-core/lib/utils/transaction.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/transaction'>;
}
declare module 'ganache-core/lib/utils/txrejectederror.js' {
  declare module.exports: $Exports<'ganache-core/lib/utils/txrejectederror'>;
}
declare module 'ganache-core/lib/webSocketServer.js' {
  declare module.exports: $Exports<'ganache-core/lib/webSocketServer'>;
}
declare module 'ganache-core/public-exports.js' {
  declare module.exports: $Exports<'ganache-core/public-exports'>;
}
