// flow-typed signature: 8cc39fbf4532e4d5722f19eb44589b10
// flow-typed version: <<STUB>>/jest-environment-node_v^24.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-environment-node/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-environment-node/build/index.js' {
  declare module.exports: $Exports<'jest-environment-node/build/index'>;
}
