// flow-typed signature: 2f9c35d46d10bf4d6f11cab39ee4e7cf
// flow-typed version: <<STUB>>/mock-express-response_v^0.2.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-express-response'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-express-response' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-express-response/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-express-response/index' {
  declare module.exports: $Exports<'mock-express-response'>;
}
declare module 'mock-express-response/index.js' {
  declare module.exports: $Exports<'mock-express-response'>;
}
declare module 'mock-express-response/utils.js' {
  declare module.exports: $Exports<'mock-express-response/utils'>;
}
