// flow-typed signature: 0c1ffa0befd68f984bec29307f69fd25
// flow-typed version: <<STUB>>/mock-express-request_v^0.2.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-express-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-express-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mock-express-request/index' {
  declare module.exports: $Exports<'mock-express-request'>;
}
declare module 'mock-express-request/index.js' {
  declare module.exports: $Exports<'mock-express-request'>;
}
