// flow-typed signature: d82e4e73ac50db98afa5458070ed18b0
// flow-typed version: <<STUB>>/nesh_v^1.7.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nesh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nesh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nesh/bin/nesh' {
  declare module.exports: any;
}

declare module 'nesh/lib/command' {
  declare module.exports: any;
}

declare module 'nesh/lib/config' {
  declare module.exports: any;
}

declare module 'nesh/lib/languages/babel' {
  declare module.exports: any;
}

declare module 'nesh/lib/languages/coffee' {
  declare module.exports: any;
}

declare module 'nesh/lib/log' {
  declare module.exports: any;
}

declare module 'nesh/lib/nesh' {
  declare module.exports: any;
}

declare module 'nesh/lib/plugins/autoload' {
  declare module.exports: any;
}

declare module 'nesh/lib/plugins/builtins' {
  declare module.exports: any;
}

declare module 'nesh/lib/plugins/doc' {
  declare module.exports: any;
}

declare module 'nesh/lib/plugins/eval' {
  declare module.exports: any;
}

declare module 'nesh/lib/plugins/history' {
  declare module.exports: any;
}

declare module 'nesh/lib/plugins/require' {
  declare module.exports: any;
}

declare module 'nesh/lib/plugins/version' {
  declare module.exports: any;
}

declare module 'nesh/lib/plugins/welcome' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nesh/bin/nesh.js' {
  declare module.exports: $Exports<'nesh/bin/nesh'>;
}
declare module 'nesh/lib/command.js' {
  declare module.exports: $Exports<'nesh/lib/command'>;
}
declare module 'nesh/lib/config.js' {
  declare module.exports: $Exports<'nesh/lib/config'>;
}
declare module 'nesh/lib/languages/babel.js' {
  declare module.exports: $Exports<'nesh/lib/languages/babel'>;
}
declare module 'nesh/lib/languages/coffee.js' {
  declare module.exports: $Exports<'nesh/lib/languages/coffee'>;
}
declare module 'nesh/lib/log.js' {
  declare module.exports: $Exports<'nesh/lib/log'>;
}
declare module 'nesh/lib/nesh.js' {
  declare module.exports: $Exports<'nesh/lib/nesh'>;
}
declare module 'nesh/lib/plugins/autoload.js' {
  declare module.exports: $Exports<'nesh/lib/plugins/autoload'>;
}
declare module 'nesh/lib/plugins/builtins.js' {
  declare module.exports: $Exports<'nesh/lib/plugins/builtins'>;
}
declare module 'nesh/lib/plugins/doc.js' {
  declare module.exports: $Exports<'nesh/lib/plugins/doc'>;
}
declare module 'nesh/lib/plugins/eval.js' {
  declare module.exports: $Exports<'nesh/lib/plugins/eval'>;
}
declare module 'nesh/lib/plugins/history.js' {
  declare module.exports: $Exports<'nesh/lib/plugins/history'>;
}
declare module 'nesh/lib/plugins/require.js' {
  declare module.exports: $Exports<'nesh/lib/plugins/require'>;
}
declare module 'nesh/lib/plugins/version.js' {
  declare module.exports: $Exports<'nesh/lib/plugins/version'>;
}
declare module 'nesh/lib/plugins/welcome.js' {
  declare module.exports: $Exports<'nesh/lib/plugins/welcome'>;
}
