// flow-typed signature: cf8691072999320229db5ee8acf524b9
// flow-typed version: <<STUB>>/nodemon-webpack-plugin_v^4.0.7/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemon-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemon-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodemon-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/dist/webpack-utils' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/src/index' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/src/webpack-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodemon-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/dist/index'>;
}
declare module 'nodemon-webpack-plugin/dist/webpack-utils.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/dist/webpack-utils'>;
}
declare module 'nodemon-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/src/index'>;
}
declare module 'nodemon-webpack-plugin/src/webpack-utils.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/src/webpack-utils'>;
}
