// flow-typed signature: 8f4ee2b503fa38047fa7bba4dcefa35d
// flow-typed version: <<STUB>>/plivo_v^4.0.7/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plivo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plivo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plivo/dist/base' {
  declare module.exports: any;
}

declare module 'plivo/dist/resources/accounts' {
  declare module.exports: any;
}

declare module 'plivo/dist/resources/applications' {
  declare module.exports: any;
}

declare module 'plivo/dist/resources/call' {
  declare module.exports: any;
}

declare module 'plivo/dist/resources/conferences' {
  declare module.exports: any;
}

declare module 'plivo/dist/resources/endpoints' {
  declare module.exports: any;
}

declare module 'plivo/dist/resources/messages' {
  declare module.exports: any;
}

declare module 'plivo/dist/resources/numbers' {
  declare module.exports: any;
}

declare module 'plivo/dist/resources/pricings' {
  declare module.exports: any;
}

declare module 'plivo/dist/resources/recordings' {
  declare module.exports: any;
}

declare module 'plivo/dist/rest/client-test' {
  declare module.exports: any;
}

declare module 'plivo/dist/rest/client' {
  declare module.exports: any;
}

declare module 'plivo/dist/rest/request-test' {
  declare module.exports: any;
}

declare module 'plivo/dist/rest/request' {
  declare module.exports: any;
}

declare module 'plivo/dist/rest/utils' {
  declare module.exports: any;
}

declare module 'plivo/dist/utils/common' {
  declare module.exports: any;
}

declare module 'plivo/dist/utils/exceptions' {
  declare module.exports: any;
}

declare module 'plivo/dist/utils/plivoxml' {
  declare module.exports: any;
}

declare module 'plivo/dist/utils/security' {
  declare module.exports: any;
}

declare module 'plivo/dist/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plivo/dist/base.js' {
  declare module.exports: $Exports<'plivo/dist/base'>;
}
declare module 'plivo/dist/resources/accounts.js' {
  declare module.exports: $Exports<'plivo/dist/resources/accounts'>;
}
declare module 'plivo/dist/resources/applications.js' {
  declare module.exports: $Exports<'plivo/dist/resources/applications'>;
}
declare module 'plivo/dist/resources/call.js' {
  declare module.exports: $Exports<'plivo/dist/resources/call'>;
}
declare module 'plivo/dist/resources/conferences.js' {
  declare module.exports: $Exports<'plivo/dist/resources/conferences'>;
}
declare module 'plivo/dist/resources/endpoints.js' {
  declare module.exports: $Exports<'plivo/dist/resources/endpoints'>;
}
declare module 'plivo/dist/resources/messages.js' {
  declare module.exports: $Exports<'plivo/dist/resources/messages'>;
}
declare module 'plivo/dist/resources/numbers.js' {
  declare module.exports: $Exports<'plivo/dist/resources/numbers'>;
}
declare module 'plivo/dist/resources/pricings.js' {
  declare module.exports: $Exports<'plivo/dist/resources/pricings'>;
}
declare module 'plivo/dist/resources/recordings.js' {
  declare module.exports: $Exports<'plivo/dist/resources/recordings'>;
}
declare module 'plivo/dist/rest/client-test.js' {
  declare module.exports: $Exports<'plivo/dist/rest/client-test'>;
}
declare module 'plivo/dist/rest/client.js' {
  declare module.exports: $Exports<'plivo/dist/rest/client'>;
}
declare module 'plivo/dist/rest/request-test.js' {
  declare module.exports: $Exports<'plivo/dist/rest/request-test'>;
}
declare module 'plivo/dist/rest/request.js' {
  declare module.exports: $Exports<'plivo/dist/rest/request'>;
}
declare module 'plivo/dist/rest/utils.js' {
  declare module.exports: $Exports<'plivo/dist/rest/utils'>;
}
declare module 'plivo/dist/utils/common.js' {
  declare module.exports: $Exports<'plivo/dist/utils/common'>;
}
declare module 'plivo/dist/utils/exceptions.js' {
  declare module.exports: $Exports<'plivo/dist/utils/exceptions'>;
}
declare module 'plivo/dist/utils/plivoxml.js' {
  declare module.exports: $Exports<'plivo/dist/utils/plivoxml'>;
}
declare module 'plivo/dist/utils/security.js' {
  declare module.exports: $Exports<'plivo/dist/utils/security'>;
}
declare module 'plivo/dist/version.js' {
  declare module.exports: $Exports<'plivo/dist/version'>;
}
