// flow-typed signature: 4cd5f6233c43c9a9a517df97a29b3690
// flow-typed version: <<STUB>>/web3-core-promievent_v^1.0.0-beta.37/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-core-promievent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-core-promievent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-core-promievent/dist/web3-core-promievent.cjs' {
  declare module.exports: any;
}

declare module 'web3-core-promievent/dist/web3-core-promievent.esm' {
  declare module.exports: any;
}

declare module 'web3-core-promievent/dist/web3-core-promievent.min' {
  declare module.exports: any;
}

declare module 'web3-core-promievent/dist/web3-core-promievent.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-core-promievent/dist/web3-core-promievent.cjs.js' {
  declare module.exports: $Exports<'web3-core-promievent/dist/web3-core-promievent.cjs'>;
}
declare module 'web3-core-promievent/dist/web3-core-promievent.esm.js' {
  declare module.exports: $Exports<'web3-core-promievent/dist/web3-core-promievent.esm'>;
}
declare module 'web3-core-promievent/dist/web3-core-promievent.min.js' {
  declare module.exports: $Exports<'web3-core-promievent/dist/web3-core-promievent.min'>;
}
declare module 'web3-core-promievent/dist/web3-core-promievent.umd.js' {
  declare module.exports: $Exports<'web3-core-promievent/dist/web3-core-promievent.umd'>;
}
